// server/mock-data.ts
import type { InsertStore, InsertItem } from "@shared/schema";

// ── San Francisco Area Grocery Stores ────────────────────────
// Real locations with accurate coordinates

export const mockStores: InsertStore[] = [
  // Trader Joe's
  {
    name: "Trader Joe's — Stonestown",
    address: "501 Buckingham Way, San Francisco, CA 94132",
    lat: 37.7289, lng: -122.4769,
    hoursJson: { daily: "8am–9pm" },
  },
  {
    name: "Trader Joe's — Masonic",
    address: "401 Bay St, San Francisco, CA 94133",
    lat: 37.8059, lng: -122.4330,
    hoursJson: { daily: "8am–9pm" },
  },
  // Safeway
  {
    name: "Safeway — Market St",
    address: "2020 Market St, San Francisco, CA 94114",
    lat: 37.7693, lng: -122.4280,
    hoursJson: { daily: "6am–11pm" },
  },
  {
    name: "Safeway — Marina",
    address: "15 Marina Blvd, San Francisco, CA 94123",
    lat: 37.8037, lng: -122.4378,
    hoursJson: { daily: "6am–11pm" },
  },
  {
    name: "Safeway — Potrero Hill",
    address: "2300 16th St, San Francisco, CA 94103",
    lat: 37.7661, lng: -122.4074,
    hoursJson: { daily: "6am–12am" },
  },
  // Whole Foods
  {
    name: "Whole Foods — SoMa",
    address: "399 4th St, San Francisco, CA 94107",
    lat: 37.7806, lng: -122.4007,
    hoursJson: { daily: "8am–10pm" },
  },
  {
    name: "Whole Foods — Noe Valley",
    address: "3950 24th St, San Francisco, CA 94114",
    lat: 37.7516, lng: -122.4285,
    hoursJson: { daily: "8am–10pm" },
  },
  // Costco
  {
    name: "Costco — South SF",
    address: "451 S Airport Blvd, South San Francisco, CA 94080",
    lat: 37.6416, lng: -122.3975,
    hoursJson: { mon_fri: "10am–8:30pm", sat: "9:30am–6pm", sun: "10am–6pm" },
  },
  // Target (grocery section)
  {
    name: "Target — Metreon",
    address: "789 Mission St, San Francisco, CA 94103",
    lat: 37.7834, lng: -122.4038,
    hoursJson: { daily: "8am–10pm" },
  },
  // Lucky / Save Mart
  {
    name: "Lucky Supermarkets — Excelsior",
    address: "5401 Mission St, San Francisco, CA 94112",
    lat: 37.7147, lng: -122.4417,
    hoursJson: { daily: "6am–12am" },
  },
  // Grocery Outlet
  {
    name: "Grocery Outlet — Mission",
    address: "2800 Mission St, San Francisco, CA 94110",
    lat: 37.7521, lng: -122.4186,
    hoursJson: { daily: "8am–9pm" },
  },
  // Sprouts
  {
    name: "Sprouts — Daly City",
    address: "2 Serramonte Center, Daly City, CA 94015",
    lat: 37.6713, lng: -122.4710,
    hoursJson: { daily: "7am–10pm" },
  },
  // Rainbow Grocery (co-op)
  {
    name: "Rainbow Grocery Cooperative",
    address: "1745 Folsom St, San Francisco, CA 94103",
    lat: 37.7699, lng: -122.4142,
    hoursJson: { daily: "9am–9pm" },
  },
  // Mollie Stone's
  {
    name: "Mollie Stone's — Pacific Heights",
    address: "2435 California St, San Francisco, CA 94115",
    lat: 37.7886, lng: -122.4343,
    hoursJson: { daily: "7am–9pm" },
  },
  // Gus's Community Market
  {
    name: "Gus's Community Market — Mission",
    address: "2111 Harrison St, San Francisco, CA 94110",
    lat: 37.7641, lng: -122.4126,
    hoursJson: { daily: "8am–9pm" },
  },
];

// ── Grocery Items ────────────────────────────────────────────
// ~60 items across produce, dairy, meat, pantry, beverages, frozen, bakery

export const mockItems: InsertItem[] = [
  // Produce
  { name: "Bananas", descriptor: "per lb", unit: "lb", organicConventional: "conventional" },
  { name: "Organic Bananas", descriptor: "per lb", unit: "lb", organicConventional: "organic" },
  { name: "Avocados", descriptor: "each", unit: "each" },
  { name: "Strawberries", descriptor: "1 lb clamshell", unit: "lb" },
  { name: "Blueberries", descriptor: "6 oz", unit: "oz" },
  { name: "Lemons", descriptor: "each", unit: "each" },
  { name: "Apples — Fuji", descriptor: "per lb", unit: "lb" },
  { name: "Apples — Honeycrisp", descriptor: "per lb", unit: "lb" },
  { name: "Tomatoes — Roma", descriptor: "per lb", unit: "lb" },
  { name: "Tomatoes — Cherry", descriptor: "1 pint", unit: "pint" },
  { name: "Russet Potatoes", descriptor: "5 lb bag", unit: "bag" },
  { name: "Yellow Onions", descriptor: "3 lb bag", unit: "bag" },
  { name: "Garlic", descriptor: "head", unit: "each" },
  { name: "Baby Spinach", descriptor: "5 oz", unit: "oz" },
  { name: "Romaine Lettuce", descriptor: "head", unit: "each" },
  { name: "Broccoli", descriptor: "per lb", unit: "lb" },
  { name: "Carrots", descriptor: "1 lb bag", unit: "bag" },
  { name: "Bell Peppers", descriptor: "each", unit: "each" },
  { name: "Cilantro", descriptor: "bunch", unit: "bunch", bunchFlag: true },
  { name: "Limes", descriptor: "each", unit: "each" },

  // Dairy & Eggs
  { name: "Whole Milk", descriptor: "1 gallon", unit: "gallon" },
  { name: "2% Milk", descriptor: "1 gallon", unit: "gallon" },
  { name: "Oat Milk", descriptor: "64 oz", unit: "oz" },
  { name: "Large Eggs", descriptor: "dozen", unit: "dozen" },
  { name: "Cage-Free Eggs", descriptor: "dozen", unit: "dozen" },
  { name: "Greek Yogurt", descriptor: "32 oz", unit: "oz" },
  { name: "Butter — Unsalted", descriptor: "1 lb", unit: "lb" },
  { name: "Cheddar Cheese", descriptor: "8 oz block", unit: "oz" },
  { name: "Shredded Mozzarella", descriptor: "8 oz", unit: "oz" },
  { name: "Cream Cheese", descriptor: "8 oz", unit: "oz" },
  { name: "Parmesan", descriptor: "5 oz wedge", unit: "oz" },

  // Meat & Seafood
  { name: "Chicken Breast — Boneless", descriptor: "per lb", unit: "lb" },
  { name: "Chicken Thighs", descriptor: "per lb", unit: "lb" },
  { name: "Ground Beef 80/20", descriptor: "per lb", unit: "lb" },
  { name: "Ground Turkey", descriptor: "per lb", unit: "lb" },
  { name: "Salmon Fillet", descriptor: "per lb", unit: "lb" },
  { name: "Bacon", descriptor: "12 oz", unit: "oz" },
  { name: "Italian Sausage", descriptor: "per lb", unit: "lb" },

  // Pantry
  { name: "White Rice", descriptor: "5 lb bag", unit: "bag" },
  { name: "Brown Rice", descriptor: "2 lb bag", unit: "bag" },
  { name: "Spaghetti", descriptor: "1 lb", unit: "lb" },
  { name: "Penne Pasta", descriptor: "1 lb", unit: "lb" },
  { name: "Marinara Sauce", descriptor: "24 oz jar", unit: "jar" },
  { name: "Olive Oil — Extra Virgin", descriptor: "16.9 oz", unit: "oz" },
  { name: "Canned Black Beans", descriptor: "15 oz", unit: "can" },
  { name: "Canned Diced Tomatoes", descriptor: "14.5 oz", unit: "can" },
  { name: "Chicken Broth", descriptor: "32 oz", unit: "oz" },
  { name: "Peanut Butter", descriptor: "16 oz", unit: "oz" },
  { name: "Honey", descriptor: "12 oz", unit: "oz" },
  { name: "All-Purpose Flour", descriptor: "5 lb", unit: "lb" },
  { name: "Granulated Sugar", descriptor: "4 lb", unit: "lb" },

  // Beverages
  { name: "Coffee — Medium Roast", descriptor: "12 oz beans", unit: "oz" },
  { name: "Green Tea", descriptor: "20 bags", unit: "box" },
  { name: "Orange Juice", descriptor: "52 oz", unit: "oz" },
  { name: "Sparkling Water", descriptor: "12-pack", unit: "pack" },

  // Frozen
  { name: "Frozen Mixed Vegetables", descriptor: "16 oz", unit: "oz" },
  { name: "Frozen Pizza", descriptor: "each", unit: "each" },
  { name: "Ice Cream — Vanilla", descriptor: "pint", unit: "pint" },

  // Bakery & Bread
  { name: "Sourdough Bread", descriptor: "loaf", unit: "loaf" },
  { name: "Whole Wheat Bread", descriptor: "loaf", unit: "loaf" },
  { name: "Tortillas — Flour", descriptor: "10 count", unit: "pack" },
];

// ── Price Data ───────────────────────────────────────────────

export type MockPriceRow = {
  storeName: string;
  itemName: string;
  price: number;
  unit?: string;
  quantity?: number;
  priceType?: string;
  isPromotion?: boolean;
  originalPrice?: number;
  promotionText?: string;
  promotionStartDate?: Date;
  promotionEndDate?: Date;
  memberPrice?: number;
  loyaltyRequired?: boolean;
};

const now = new Date();
const inTwoWeeks = new Date(Date.now() + 14 * 24 * 60 * 60 * 1000);

// Helper to build prices for a store
type PriceEntry = [string, number, Partial<Omit<MockPriceRow, "storeName" | "itemName" | "price">>?];

function buildPrices(storeName: string, entries: PriceEntry[]): MockPriceRow[] {
  return entries.map(([itemName, price, extra]) => ({
    storeName,
    itemName,
    price,
    ...extra,
  }));
}

export const mockPricesByStore: MockPriceRow[] = [

  // ── Trader Joe's — Stonestown ─────────────────
  // Known for low prices, no loyalty program, unique house brands
  ...buildPrices("Trader Joe's — Stonestown", [
    ["Bananas", 0.23, { unit: "each" }],
    ["Organic Bananas", 0.29, { unit: "each" }],
    ["Avocados", 1.29],
    ["Strawberries", 3.49],
    ["Blueberries", 2.49],
    ["Lemons", 0.29],
    ["Apples — Fuji", 1.69, { unit: "lb" }],
    ["Tomatoes — Roma", 1.99, { unit: "lb" }],
    ["Tomatoes — Cherry", 2.49],
    ["Russet Potatoes", 3.49],
    ["Yellow Onions", 1.99],
    ["Garlic", 0.50],
    ["Baby Spinach", 2.29],
    ["Broccoli", 1.79, { unit: "lb" }],
    ["Carrots", 0.99],
    ["Bell Peppers", 0.79],
    ["Cilantro", 0.69],
    ["Limes", 0.25],
    ["Whole Milk", 4.29, { unit: "gallon" }],
    ["2% Milk", 4.29, { unit: "gallon" }],
    ["Oat Milk", 3.99],
    ["Large Eggs", 3.29, { unit: "dozen" }],
    ["Cage-Free Eggs", 4.49, { unit: "dozen" }],
    ["Greek Yogurt", 4.99],
    ["Butter — Unsalted", 3.49],
    ["Cheddar Cheese", 2.99],
    ["Shredded Mozzarella", 2.99],
    ["Cream Cheese", 2.29],
    ["Parmesan", 4.49],
    ["Chicken Breast — Boneless", 3.99, { unit: "lb" }],
    ["Chicken Thighs", 2.49, { unit: "lb" }],
    ["Ground Beef 80/20", 5.49, { unit: "lb" }],
    ["Ground Turkey", 4.49, { unit: "lb" }],
    ["Salmon Fillet", 9.99, { unit: "lb" }],
    ["Bacon", 4.99],
    ["Italian Sausage", 3.99, { unit: "lb" }],
    ["White Rice", 4.99],
    ["Brown Rice", 2.99],
    ["Spaghetti", 0.99],
    ["Penne Pasta", 0.99],
    ["Marinara Sauce", 2.49],
    ["Olive Oil — Extra Virgin", 5.99],
    ["Canned Black Beans", 0.99],
    ["Canned Diced Tomatoes", 0.99],
    ["Chicken Broth", 1.99],
    ["Peanut Butter", 2.99],
    ["Honey", 4.49],
    ["All-Purpose Flour", 3.29],
    ["Granulated Sugar", 2.99],
    ["Coffee — Medium Roast", 8.99],
    ["Green Tea", 2.49],
    ["Orange Juice", 3.49],
    ["Sparkling Water", 3.99],
    ["Frozen Mixed Vegetables", 1.99],
    ["Frozen Pizza", 4.49],
    ["Ice Cream — Vanilla", 3.99],
    ["Sourdough Bread", 3.49],
    ["Whole Wheat Bread", 2.99],
    ["Tortillas — Flour", 2.29],
  ]),

  // ── Trader Joe's — Masonic ────────────────────
  // Same TJ prices, minor variance
  ...buildPrices("Trader Joe's — Masonic", [
    ["Bananas", 0.23, { unit: "each" }],
    ["Organic Bananas", 0.29, { unit: "each" }],
    ["Avocados", 1.29],
    ["Strawberries", 3.49],
    ["Blueberries", 2.49],
    ["Lemons", 0.29],
    ["Apples — Fuji", 1.69, { unit: "lb" }],
    ["Tomatoes — Cherry", 2.49],
    ["Russet Potatoes", 3.49],
    ["Baby Spinach", 2.29],
    ["Carrots", 0.99],
    ["Cilantro", 0.69],
    ["Whole Milk", 4.29, { unit: "gallon" }],
    ["2% Milk", 4.29, { unit: "gallon" }],
    ["Oat Milk", 3.99],
    ["Large Eggs", 3.29, { unit: "dozen" }],
    ["Cage-Free Eggs", 4.49, { unit: "dozen" }],
    ["Greek Yogurt", 4.99],
    ["Butter — Unsalted", 3.49],
    ["Cheddar Cheese", 2.99],
    ["Cream Cheese", 2.29],
    ["Chicken Breast — Boneless", 3.99, { unit: "lb" }],
    ["Ground Beef 80/20", 5.49, { unit: "lb" }],
    ["Salmon Fillet", 9.99, { unit: "lb" }],
    ["Bacon", 4.99],
    ["Spaghetti", 0.99],
    ["Penne Pasta", 0.99],
    ["Marinara Sauce", 2.49],
    ["Olive Oil — Extra Virgin", 5.99],
    ["Canned Black Beans", 0.99],
    ["Chicken Broth", 1.99],
    ["Peanut Butter", 2.99],
    ["Coffee — Medium Roast", 8.99],
    ["Orange Juice", 3.49],
    ["Sparkling Water", 3.99],
    ["Frozen Pizza", 4.49],
    ["Ice Cream — Vanilla", 3.99],
    ["Sourdough Bread", 3.49],
    ["Tortillas — Flour", 2.29],
  ]),

  // ── Safeway — Market St ───────────────────────
  // Higher shelf prices, Club Card deals, weekly promos
  ...buildPrices("Safeway — Market St", [
    ["Bananas", 0.69, { unit: "lb" }],
    ["Organic Bananas", 0.89, { unit: "lb" }],
    ["Avocados", 1.99, { isPromotion: true, originalPrice: 2.50, promotionText: "Club Price", promotionStartDate: now, promotionEndDate: inTwoWeeks, loyaltyRequired: true }],
    ["Strawberries", 3.99, { memberPrice: 2.99, loyaltyRequired: true }],
    ["Blueberries", 3.49, { memberPrice: 2.99, loyaltyRequired: true }],
    ["Lemons", 0.75],
    ["Apples — Fuji", 2.29, { unit: "lb" }],
    ["Apples — Honeycrisp", 3.49, { unit: "lb", memberPrice: 2.49, loyaltyRequired: true }],
    ["Tomatoes — Roma", 2.29, { unit: "lb" }],
    ["Tomatoes — Cherry", 3.49],
    ["Russet Potatoes", 4.99],
    ["Yellow Onions", 2.99],
    ["Garlic", 0.75],
    ["Baby Spinach", 3.49, { memberPrice: 2.99, loyaltyRequired: true }],
    ["Romaine Lettuce", 1.99],
    ["Broccoli", 2.29, { unit: "lb" }],
    ["Carrots", 1.49],
    ["Bell Peppers", 1.29],
    ["Cilantro", 0.99],
    ["Limes", 0.50],
    ["Whole Milk", 5.49, { unit: "gallon" }],
    ["2% Milk", 5.49, { unit: "gallon" }],
    ["Oat Milk", 4.99],
    ["Large Eggs", 4.49, { unit: "dozen", isPromotion: true, originalPrice: 5.49, promotionText: "Club Price", promotionStartDate: now, promotionEndDate: inTwoWeeks, loyaltyRequired: true }],
    ["Cage-Free Eggs", 5.99, { unit: "dozen" }],
    ["Greek Yogurt", 5.99],
    ["Butter — Unsalted", 4.99, { memberPrice: 3.99, loyaltyRequired: true }],
    ["Cheddar Cheese", 3.99],
    ["Shredded Mozzarella", 3.99],
    ["Cream Cheese", 3.29],
    ["Parmesan", 5.99],
    ["Chicken Breast — Boneless", 5.49, { unit: "lb", isPromotion: true, originalPrice: 7.49, promotionText: "Weekly Special", promotionStartDate: now, promotionEndDate: inTwoWeeks }],
    ["Chicken Thighs", 3.49, { unit: "lb" }],
    ["Ground Beef 80/20", 6.49, { unit: "lb" }],
    ["Ground Turkey", 5.49, { unit: "lb" }],
    ["Salmon Fillet", 12.99, { unit: "lb", memberPrice: 9.99, loyaltyRequired: true }],
    ["Bacon", 6.99, { memberPrice: 5.49, loyaltyRequired: true }],
    ["Italian Sausage", 5.49, { unit: "lb" }],
    ["White Rice", 5.99],
    ["Brown Rice", 3.99],
    ["Spaghetti", 1.69],
    ["Penne Pasta", 1.69],
    ["Marinara Sauce", 3.49],
    ["Olive Oil — Extra Virgin", 7.99],
    ["Canned Black Beans", 1.49],
    ["Canned Diced Tomatoes", 1.29],
    ["Chicken Broth", 2.49],
    ["Peanut Butter", 3.99],
    ["Honey", 6.49],
    ["All-Purpose Flour", 3.99],
    ["Granulated Sugar", 3.49],
    ["Coffee — Medium Roast", 9.99],
    ["Green Tea", 3.49],
    ["Orange Juice", 4.49, { memberPrice: 3.49, loyaltyRequired: true }],
    ["Sparkling Water", 5.49, { memberPrice: 3.99, loyaltyRequired: true }],
    ["Frozen Mixed Vegetables", 2.49],
    ["Frozen Pizza", 6.49, { isPromotion: true, originalPrice: 8.99, promotionText: "2 for $12", promotionStartDate: now, promotionEndDate: inTwoWeeks }],
    ["Ice Cream — Vanilla", 5.99],
    ["Sourdough Bread", 4.49],
    ["Whole Wheat Bread", 3.99],
    ["Tortillas — Flour", 3.29],
  ]),

  // ── Safeway — Marina ──────────────────────────
  // Same as Market St with minor variance
  ...buildPrices("Safeway — Marina", [
    ["Bananas", 0.69, { unit: "lb" }],
    ["Avocados", 1.99],
    ["Strawberries", 3.99, { memberPrice: 2.99, loyaltyRequired: true }],
    ["Lemons", 0.75],
    ["Apples — Fuji", 2.29, { unit: "lb" }],
    ["Tomatoes — Roma", 2.29, { unit: "lb" }],
    ["Russet Potatoes", 4.99],
    ["Baby Spinach", 3.49],
    ["Romaine Lettuce", 1.99],
    ["Broccoli", 2.29, { unit: "lb" }],
    ["Whole Milk", 5.49, { unit: "gallon" }],
    ["Large Eggs", 4.49, { unit: "dozen", memberPrice: 3.49, loyaltyRequired: true }],
    ["Greek Yogurt", 5.99],
    ["Butter — Unsalted", 4.99],
    ["Cheddar Cheese", 3.99],
    ["Chicken Breast — Boneless", 5.49, { unit: "lb" }],
    ["Ground Beef 80/20", 6.49, { unit: "lb" }],
    ["Salmon Fillet", 12.99, { unit: "lb" }],
    ["Bacon", 6.99],
    ["Spaghetti", 1.69],
    ["Marinara Sauce", 3.49],
    ["Olive Oil — Extra Virgin", 7.99],
    ["Canned Black Beans", 1.49],
    ["Coffee — Medium Roast", 9.99],
    ["Orange Juice", 4.49],
    ["Sourdough Bread", 4.49],
    ["Tortillas — Flour", 3.29],
  ]),

  // ── Safeway — Potrero Hill ────────────────────
  ...buildPrices("Safeway — Potrero Hill", [
    ["Bananas", 0.69, { unit: "lb" }],
    ["Avocados", 1.99],
    ["Strawberries", 3.99],
    ["Blueberries", 3.49],
    ["Apples — Fuji", 2.29, { unit: "lb" }],
    ["Tomatoes — Cherry", 3.49],
    ["Russet Potatoes", 4.99],
    ["Yellow Onions", 2.99],
    ["Garlic", 0.75],
    ["Baby Spinach", 3.49],
    ["Bell Peppers", 1.29],
    ["Whole Milk", 5.49, { unit: "gallon" }],
    ["2% Milk", 5.49, { unit: "gallon" }],
    ["Large Eggs", 4.49, { unit: "dozen" }],
    ["Cage-Free Eggs", 5.99, { unit: "dozen" }],
    ["Cheddar Cheese", 3.99],
    ["Chicken Breast — Boneless", 5.49, { unit: "lb" }],
    ["Chicken Thighs", 3.49, { unit: "lb" }],
    ["Ground Beef 80/20", 6.49, { unit: "lb" }],
    ["Salmon Fillet", 12.99, { unit: "lb" }],
    ["White Rice", 5.99],
    ["Spaghetti", 1.69],
    ["Penne Pasta", 1.69],
    ["Marinara Sauce", 3.49],
    ["Canned Diced Tomatoes", 1.29],
    ["Coffee — Medium Roast", 9.99],
    ["Sparkling Water", 5.49],
    ["Frozen Pizza", 6.49],
    ["Sourdough Bread", 4.49],
    ["Whole Wheat Bread", 3.99],
  ]),

  // ── Whole Foods — SoMa ────────────────────────
  // Premium prices, Prime member discounts
  ...buildPrices("Whole Foods — SoMa", [
    ["Bananas", 0.79, { unit: "lb" }],
    ["Organic Bananas", 0.69, { unit: "lb" }],
    ["Avocados", 2.49, { memberPrice: 1.69, loyaltyRequired: true }],
    ["Strawberries", 4.99, { memberPrice: 3.99, loyaltyRequired: true }],
    ["Blueberries", 4.49, { memberPrice: 3.49, loyaltyRequired: true }],
    ["Lemons", 0.69],
    ["Apples — Fuji", 2.49, { unit: "lb" }],
    ["Apples — Honeycrisp", 3.99, { unit: "lb" }],
    ["Tomatoes — Roma", 2.99, { unit: "lb" }],
    ["Tomatoes — Cherry", 3.99],
    ["Russet Potatoes", 5.99],
    ["Yellow Onions", 2.49],
    ["Garlic", 0.79],
    ["Baby Spinach", 3.99],
    ["Romaine Lettuce", 2.49],
    ["Broccoli", 2.99, { unit: "lb" }],
    ["Carrots", 1.49],
    ["Bell Peppers", 1.49],
    ["Cilantro", 1.29],
    ["Limes", 0.50],
    ["Whole Milk", 5.99, { unit: "gallon", memberPrice: 4.99, loyaltyRequired: true }],
    ["2% Milk", 5.99, { unit: "gallon" }],
    ["Oat Milk", 4.99],
    ["Large Eggs", 5.49, { unit: "dozen" }],
    ["Cage-Free Eggs", 5.99, { unit: "dozen", memberPrice: 4.99, loyaltyRequired: true }],
    ["Greek Yogurt", 6.49],
    ["Butter — Unsalted", 5.49],
    ["Cheddar Cheese", 4.49],
    ["Shredded Mozzarella", 4.49],
    ["Cream Cheese", 3.49],
    ["Parmesan", 6.99],
    ["Chicken Breast — Boneless", 7.99, { unit: "lb", memberPrice: 5.99, loyaltyRequired: true }],
    ["Chicken Thighs", 4.49, { unit: "lb" }],
    ["Ground Beef 80/20", 7.99, { unit: "lb" }],
    ["Ground Turkey", 6.49, { unit: "lb" }],
    ["Salmon Fillet", 14.99, { unit: "lb", memberPrice: 11.99, loyaltyRequired: true }],
    ["Bacon", 7.99],
    ["Italian Sausage", 6.49, { unit: "lb" }],
    ["White Rice", 6.49],
    ["Brown Rice", 4.49],
    ["Spaghetti", 1.99],
    ["Penne Pasta", 1.99],
    ["Marinara Sauce", 4.49],
    ["Olive Oil — Extra Virgin", 8.99],
    ["Canned Black Beans", 1.49],
    ["Canned Diced Tomatoes", 1.49],
    ["Chicken Broth", 3.49],
    ["Peanut Butter", 4.99],
    ["Honey", 7.99],
    ["All-Purpose Flour", 4.99],
    ["Granulated Sugar", 4.49],
    ["Coffee — Medium Roast", 11.99],
    ["Green Tea", 4.49],
    ["Orange Juice", 5.49],
    ["Sparkling Water", 5.99],
    ["Frozen Mixed Vegetables", 2.99],
    ["Frozen Pizza", 7.99],
    ["Ice Cream — Vanilla", 5.99],
    ["Sourdough Bread", 5.49],
    ["Whole Wheat Bread", 4.49],
    ["Tortillas — Flour", 3.99],
  ]),

  // ── Whole Foods — Noe Valley ──────────────────
  ...buildPrices("Whole Foods — Noe Valley", [
    ["Bananas", 0.79, { unit: "lb" }],
    ["Organic Bananas", 0.69, { unit: "lb" }],
    ["Avocados", 2.49, { memberPrice: 1.69, loyaltyRequired: true }],
    ["Strawberries", 4.99],
    ["Blueberries", 4.49],
    ["Apples — Honeycrisp", 3.99, { unit: "lb" }],
    ["Tomatoes — Cherry", 3.99],
    ["Baby Spinach", 3.99],
    ["Romaine Lettuce", 2.49],
    ["Broccoli", 2.99, { unit: "lb" }],
    ["Cilantro", 1.29],
    ["Whole Milk", 5.99, { unit: "gallon" }],
    ["Oat Milk", 4.99],
    ["Large Eggs", 5.49, { unit: "dozen" }],
    ["Cage-Free Eggs", 5.99, { unit: "dozen" }],
    ["Greek Yogurt", 6.49],
    ["Cheddar Cheese", 4.49],
    ["Parmesan", 6.99],
    ["Chicken Breast — Boneless", 7.99, { unit: "lb" }],
    ["Ground Beef 80/20", 7.99, { unit: "lb" }],
    ["Salmon Fillet", 14.99, { unit: "lb" }],
    ["Spaghetti", 1.99],
    ["Olive Oil — Extra Virgin", 8.99],
    ["Coffee — Medium Roast", 11.99],
    ["Sourdough Bread", 5.49],
    ["Ice Cream — Vanilla", 5.99],
  ]),

  // ── Costco — South SF ─────────────────────────
  // Bulk pricing, membership required for everything
  ...buildPrices("Costco — South SF", [
    ["Bananas", 1.49, { unit: "3 lb", quantity: 3, loyaltyRequired: true }],
    ["Organic Bananas", 1.99, { unit: "3 lb", quantity: 3, loyaltyRequired: true }],
    ["Avocados", 7.99, { unit: "6-pack", loyaltyRequired: true }],
    ["Strawberries", 5.99, { unit: "2 lb", quantity: 2, loyaltyRequired: true }],
    ["Blueberries", 6.99, { unit: "18 oz", loyaltyRequired: true }],
    ["Apples — Fuji", 7.99, { unit: "5 lb", quantity: 5, loyaltyRequired: true }],
    ["Russet Potatoes", 5.99, { unit: "10 lb", quantity: 10, loyaltyRequired: true }],
    ["Baby Spinach", 4.49, { unit: "16 oz", loyaltyRequired: true }],
    ["Romaine Lettuce", 3.99, { unit: "6-pack", loyaltyRequired: true }],
    ["Bell Peppers", 5.99, { unit: "6-pack", loyaltyRequired: true }],
    ["Whole Milk", 7.49, { unit: "2 gallon", quantity: 2, loyaltyRequired: true }],
    ["Large Eggs", 5.99, { unit: "2 dozen", quantity: 2, loyaltyRequired: true }],
    ["Cage-Free Eggs", 7.99, { unit: "2 dozen", quantity: 2, loyaltyRequired: true }],
    ["Greek Yogurt", 6.99, { unit: "48 oz", loyaltyRequired: true }],
    ["Butter — Unsalted", 7.99, { unit: "2 lb", quantity: 2, loyaltyRequired: true }],
    ["Cheddar Cheese", 8.49, { unit: "2 lb", quantity: 2, loyaltyRequired: true }],
    ["Shredded Mozzarella", 8.49, { unit: "2.5 lb", loyaltyRequired: true }],
    ["Parmesan", 12.99, { unit: "24 oz wedge", loyaltyRequired: true }],
    ["Chicken Breast — Boneless", 3.49, { unit: "lb", loyaltyRequired: true }],
    ["Ground Beef 80/20", 5.29, { unit: "lb", loyaltyRequired: true }],
    ["Salmon Fillet", 11.49, { unit: "lb", loyaltyRequired: true }],
    ["Bacon", 12.99, { unit: "2 lb", quantity: 2, loyaltyRequired: true }],
    ["Italian Sausage", 3.99, { unit: "lb", loyaltyRequired: true }],
    ["White Rice", 9.99, { unit: "25 lb", quantity: 25, loyaltyRequired: true }],
    ["Olive Oil — Extra Virgin", 12.99, { unit: "33.8 oz", loyaltyRequired: true }],
    ["Canned Black Beans", 7.49, { unit: "8-pack", loyaltyRequired: true }],
    ["Peanut Butter", 8.99, { unit: "48 oz", loyaltyRequired: true }],
    ["Honey", 11.99, { unit: "3 lb", quantity: 3, loyaltyRequired: true }],
    ["Coffee — Medium Roast", 14.99, { unit: "2.5 lb", loyaltyRequired: true }],
    ["Sparkling Water", 9.99, { unit: "24-pack", loyaltyRequired: true }],
    ["Frozen Pizza", 11.99, { unit: "4-pack", loyaltyRequired: true }],
    ["Sourdough Bread", 4.49, { unit: "2-pack", loyaltyRequired: true }],
    ["Tortillas — Flour", 3.99, { unit: "20 count", loyaltyRequired: true }],
  ]),

  // ── Target — Metreon ──────────────────────────
  // Competitive prices, good selection, Circle deals
  ...buildPrices("Target — Metreon", [
    ["Bananas", 0.59, { unit: "lb" }],
    ["Avocados", 1.49],
    ["Strawberries", 3.49],
    ["Blueberries", 2.99],
    ["Lemons", 0.50],
    ["Apples — Fuji", 1.99, { unit: "lb" }],
    ["Tomatoes — Cherry", 2.99],
    ["Russet Potatoes", 4.49],
    ["Yellow Onions", 2.49],
    ["Baby Spinach", 2.99],
    ["Carrots", 1.29],
    ["Bell Peppers", 0.99],
    ["Whole Milk", 4.79, { unit: "gallon" }],
    ["2% Milk", 4.79, { unit: "gallon" }],
    ["Oat Milk", 4.29],
    ["Large Eggs", 3.99, { unit: "dozen" }],
    ["Cage-Free Eggs", 5.29, { unit: "dozen" }],
    ["Greek Yogurt", 5.29],
    ["Butter — Unsalted", 4.29],
    ["Cheddar Cheese", 3.29],
    ["Shredded Mozzarella", 3.29],
    ["Cream Cheese", 2.49],
    ["Chicken Breast — Boneless", 4.99, { unit: "lb" }],
    ["Ground Beef 80/20", 5.99, { unit: "lb" }],
    ["Ground Turkey", 4.99, { unit: "lb" }],
    ["Bacon", 5.99],
    ["White Rice", 5.49],
    ["Brown Rice", 3.29],
    ["Spaghetti", 1.29],
    ["Penne Pasta", 1.29],
    ["Marinara Sauce", 2.99],
    ["Olive Oil — Extra Virgin", 6.99],
    ["Canned Black Beans", 1.09],
    ["Canned Diced Tomatoes", 1.09],
    ["Chicken Broth", 2.29],
    ["Peanut Butter", 3.49],
    ["Honey", 5.49],
    ["All-Purpose Flour", 3.49],
    ["Granulated Sugar", 2.99],
    ["Coffee — Medium Roast", 8.49],
    ["Green Tea", 2.99],
    ["Orange Juice", 3.99],
    ["Sparkling Water", 4.49],
    ["Frozen Mixed Vegetables", 2.29],
    ["Frozen Pizza", 5.49],
    ["Ice Cream — Vanilla", 4.49],
    ["Sourdough Bread", 3.99],
    ["Whole Wheat Bread", 3.29],
    ["Tortillas — Flour", 2.79],
  ]),

  // ── Lucky Supermarkets — Excelsior ────────────
  // Budget-friendly, good deals on basics
  ...buildPrices("Lucky Supermarkets — Excelsior", [
    ["Bananas", 0.59, { unit: "lb" }],
    ["Avocados", 1.29],
    ["Strawberries", 2.99, { isPromotion: true, originalPrice: 3.99, promotionText: "Weekly Ad", promotionStartDate: now, promotionEndDate: inTwoWeeks }],
    ["Lemons", 0.39],
    ["Apples — Fuji", 1.79, { unit: "lb" }],
    ["Tomatoes — Roma", 1.49, { unit: "lb" }],
    ["Russet Potatoes", 3.99],
    ["Yellow Onions", 1.99],
    ["Garlic", 0.50],
    ["Baby Spinach", 2.99],
    ["Romaine Lettuce", 1.49],
    ["Broccoli", 1.49, { unit: "lb" }],
    ["Carrots", 0.99],
    ["Bell Peppers", 0.89],
    ["Cilantro", 0.59],
    ["Limes", 0.25],
    ["Whole Milk", 4.49, { unit: "gallon" }],
    ["2% Milk", 4.49, { unit: "gallon" }],
    ["Large Eggs", 3.49, { unit: "dozen" }],
    ["Greek Yogurt", 4.99],
    ["Butter — Unsalted", 3.99],
    ["Cheddar Cheese", 2.99],
    ["Cream Cheese", 2.29],
    ["Chicken Breast — Boneless", 4.29, { unit: "lb" }],
    ["Chicken Thighs", 2.29, { unit: "lb" }],
    ["Ground Beef 80/20", 5.29, { unit: "lb" }],
    ["Ground Turkey", 4.29, { unit: "lb" }],
    ["Bacon", 5.49],
    ["Italian Sausage", 3.99, { unit: "lb" }],
    ["White Rice", 4.49],
    ["Spaghetti", 1.19],
    ["Penne Pasta", 1.19],
    ["Marinara Sauce", 2.29],
    ["Olive Oil — Extra Virgin", 5.99],
    ["Canned Black Beans", 0.89],
    ["Canned Diced Tomatoes", 0.89],
    ["Chicken Broth", 1.79],
    ["Peanut Butter", 2.99],
    ["All-Purpose Flour", 2.99],
    ["Granulated Sugar", 2.69],
    ["Coffee — Medium Roast", 7.99],
    ["Orange Juice", 3.49],
    ["Frozen Mixed Vegetables", 1.79],
    ["Frozen Pizza", 4.99],
    ["Sourdough Bread", 3.49],
    ["Whole Wheat Bread", 2.99],
    ["Tortillas — Flour", 2.49],
  ]),

  // ── Grocery Outlet — Mission ──────────────────
  // Deep discount, limited/rotating selection
  ...buildPrices("Grocery Outlet — Mission", [
    ["Bananas", 0.49, { unit: "lb" }],
    ["Avocados", 0.99],
    ["Strawberries", 2.49],
    ["Blueberries", 1.99],
    ["Apples — Fuji", 1.29, { unit: "lb" }],
    ["Tomatoes — Roma", 1.29, { unit: "lb" }],
    ["Russet Potatoes", 2.99],
    ["Yellow Onions", 1.49],
    ["Baby Spinach", 1.99],
    ["Carrots", 0.79],
    ["Whole Milk", 3.99, { unit: "gallon" }],
    ["Large Eggs", 2.99, { unit: "dozen" }],
    ["Greek Yogurt", 3.99],
    ["Butter — Unsalted", 2.99],
    ["Cheddar Cheese", 2.49],
    ["Cream Cheese", 1.79],
    ["Chicken Breast — Boneless", 3.49, { unit: "lb" }],
    ["Ground Beef 80/20", 4.49, { unit: "lb" }],
    ["Bacon", 3.99],
    ["White Rice", 3.99],
    ["Spaghetti", 0.79],
    ["Penne Pasta", 0.79],
    ["Marinara Sauce", 1.99],
    ["Olive Oil — Extra Virgin", 4.99],
    ["Canned Black Beans", 0.69],
    ["Canned Diced Tomatoes", 0.69],
    ["Peanut Butter", 2.49],
    ["Coffee — Medium Roast", 5.99],
    ["Sparkling Water", 3.49],
    ["Frozen Mixed Vegetables", 1.49],
    ["Frozen Pizza", 3.49],
    ["Ice Cream — Vanilla", 2.99],
    ["Sourdough Bread", 2.49],
    ["Whole Wheat Bread", 1.99],
    ["Tortillas — Flour", 1.79],
  ]),

  // ── Sprouts — Daly City ───────────────────────
  // Natural/organic focus, competitive produce
  ...buildPrices("Sprouts — Daly City", [
    ["Bananas", 0.59, { unit: "lb" }],
    ["Organic Bananas", 0.69, { unit: "lb" }],
    ["Avocados", 1.25],
    ["Strawberries", 2.99, { isPromotion: true, originalPrice: 3.99, promotionText: "Weekly Double!", promotionStartDate: now, promotionEndDate: inTwoWeeks }],
    ["Blueberries", 2.49],
    ["Lemons", 0.33],
    ["Apples — Fuji", 1.49, { unit: "lb" }],
    ["Apples — Honeycrisp", 2.49, { unit: "lb" }],
    ["Tomatoes — Roma", 1.29, { unit: "lb" }],
    ["Tomatoes — Cherry", 2.49],
    ["Russet Potatoes", 3.99],
    ["Yellow Onions", 1.29],
    ["Garlic", 0.50],
    ["Baby Spinach", 2.49],
    ["Romaine Lettuce", 1.29],
    ["Broccoli", 1.49, { unit: "lb" }],
    ["Carrots", 0.99],
    ["Bell Peppers", 0.99],
    ["Cilantro", 0.50],
    ["Limes", 0.25],
    ["Whole Milk", 4.99, { unit: "gallon" }],
    ["2% Milk", 4.99, { unit: "gallon" }],
    ["Oat Milk", 3.99],
    ["Large Eggs", 3.99, { unit: "dozen" }],
    ["Cage-Free Eggs", 4.99, { unit: "dozen" }],
    ["Greek Yogurt", 4.99],
    ["Butter — Unsalted", 3.99],
    ["Cheddar Cheese", 3.49],
    ["Cream Cheese", 2.49],
    ["Parmesan", 4.99],
    ["Chicken Breast — Boneless", 4.49, { unit: "lb" }],
    ["Chicken Thighs", 2.99, { unit: "lb" }],
    ["Ground Beef 80/20", 5.99, { unit: "lb" }],
    ["Ground Turkey", 4.99, { unit: "lb" }],
    ["Salmon Fillet", 9.99, { unit: "lb" }],
    ["Bacon", 5.49],
    ["Italian Sausage", 4.49, { unit: "lb" }],
    ["White Rice", 4.99],
    ["Brown Rice", 2.99],
    ["Spaghetti", 1.29],
    ["Marinara Sauce", 2.99],
    ["Olive Oil — Extra Virgin", 5.99],
    ["Canned Black Beans", 0.99],
    ["Canned Diced Tomatoes", 0.99],
    ["Chicken Broth", 1.99],
    ["Peanut Butter", 3.49],
    ["Honey", 4.99],
    ["Coffee — Medium Roast", 7.99],
    ["Green Tea", 2.99],
    ["Orange Juice", 3.99],
    ["Frozen Mixed Vegetables", 1.99],
    ["Ice Cream — Vanilla", 3.99],
    ["Sourdough Bread", 3.49],
    ["Whole Wheat Bread", 2.99],
    ["Tortillas — Flour", 2.49],
  ]),

  // ── Rainbow Grocery Cooperative ───────────────
  // Bulk bins, organic focus, worker-owned co-op
  ...buildPrices("Rainbow Grocery Cooperative", [
    ["Organic Bananas", 0.79, { unit: "lb" }],
    ["Avocados", 1.79],
    ["Strawberries", 4.49],
    ["Blueberries", 3.99],
    ["Lemons", 0.50],
    ["Apples — Fuji", 2.29, { unit: "lb" }],
    ["Tomatoes — Cherry", 3.49],
    ["Yellow Onions", 1.79],
    ["Garlic", 0.69],
    ["Baby Spinach", 3.49],
    ["Romaine Lettuce", 2.29],
    ["Broccoli", 2.49, { unit: "lb" }],
    ["Cilantro", 0.99],
    ["Oat Milk", 4.49],
    ["Cage-Free Eggs", 5.49, { unit: "dozen" }],
    ["Greek Yogurt", 5.99],
    ["Butter — Unsalted", 4.99],
    ["Cheddar Cheese", 3.99],
    ["Parmesan", 5.99],
    ["Brown Rice", 2.49],
    ["Spaghetti", 1.49],
    ["Penne Pasta", 1.49],
    ["Marinara Sauce", 3.49],
    ["Olive Oil — Extra Virgin", 7.49],
    ["Canned Black Beans", 1.29],
    ["Canned Diced Tomatoes", 1.29],
    ["Peanut Butter", 4.49],
    ["Honey", 6.99],
    ["All-Purpose Flour", 3.49],
    ["Coffee — Medium Roast", 10.99],
    ["Green Tea", 3.99],
    ["Sourdough Bread", 4.99],
    ["Tortillas — Flour", 3.49],
  ]),

  // ── Mollie Stone's — Pacific Heights ──────────
  // Upscale neighborhood market, premium pricing
  ...buildPrices("Mollie Stone's — Pacific Heights", [
    ["Bananas", 0.79, { unit: "lb" }],
    ["Organic Bananas", 0.89, { unit: "lb" }],
    ["Avocados", 2.29],
    ["Strawberries", 4.99],
    ["Blueberries", 4.49],
    ["Lemons", 0.69],
    ["Apples — Honeycrisp", 3.99, { unit: "lb" }],
    ["Tomatoes — Cherry", 3.99],
    ["Baby Spinach", 3.99],
    ["Romaine Lettuce", 2.49],
    ["Broccoli", 2.49, { unit: "lb" }],
    ["Whole Milk", 5.49, { unit: "gallon" }],
    ["2% Milk", 5.49, { unit: "gallon" }],
    ["Oat Milk", 4.99],
    ["Large Eggs", 4.99, { unit: "dozen" }],
    ["Cage-Free Eggs", 6.49, { unit: "dozen" }],
    ["Greek Yogurt", 5.99],
    ["Butter — Unsalted", 5.49],
    ["Cheddar Cheese", 4.49],
    ["Parmesan", 6.49],
    ["Chicken Breast — Boneless", 7.49, { unit: "lb" }],
    ["Ground Beef 80/20", 7.99, { unit: "lb" }],
    ["Salmon Fillet", 15.99, { unit: "lb" }],
    ["Bacon", 7.49],
    ["Olive Oil — Extra Virgin", 8.99],
    ["Coffee — Medium Roast", 12.99],
    ["Orange Juice", 5.49],
    ["Ice Cream — Vanilla", 5.99],
    ["Sourdough Bread", 5.49],
  ]),

  // ── Gus's Community Market — Mission ──────────
  // Local neighborhood market, moderate prices
  ...buildPrices("Gus's Community Market — Mission", [
    ["Bananas", 0.69, { unit: "lb" }],
    ["Avocados", 1.49],
    ["Strawberries", 3.49],
    ["Blueberries", 2.99],
    ["Lemons", 0.50],
    ["Apples — Fuji", 1.99, { unit: "lb" }],
    ["Tomatoes — Roma", 1.99, { unit: "lb" }],
    ["Tomatoes — Cherry", 2.99],
    ["Russet Potatoes", 3.99],
    ["Yellow Onions", 1.79],
    ["Garlic", 0.59],
    ["Baby Spinach", 2.99],
    ["Romaine Lettuce", 1.79],
    ["Carrots", 1.19],
    ["Bell Peppers", 0.99],
    ["Cilantro", 0.69],
    ["Whole Milk", 4.99, { unit: "gallon" }],
    ["2% Milk", 4.99, { unit: "gallon" }],
    ["Large Eggs", 3.99, { unit: "dozen" }],
    ["Cage-Free Eggs", 5.29, { unit: "dozen" }],
    ["Greek Yogurt", 5.29],
    ["Butter — Unsalted", 4.29],
    ["Cheddar Cheese", 3.49],
    ["Cream Cheese", 2.69],
    ["Chicken Breast — Boneless", 5.49, { unit: "lb" }],
    ["Chicken Thighs", 2.99, { unit: "lb" }],
    ["Ground Beef 80/20", 5.99, { unit: "lb" }],
    ["Salmon Fillet", 11.99, { unit: "lb" }],
    ["Bacon", 5.99],
    ["Spaghetti", 1.49],
    ["Marinara Sauce", 2.99],
    ["Olive Oil — Extra Virgin", 6.99],
    ["Canned Black Beans", 1.09],
    ["Canned Diced Tomatoes", 1.09],
    ["Coffee — Medium Roast", 9.49],
    ["Orange Juice", 3.99],
    ["Sparkling Water", 4.49],
    ["Frozen Pizza", 5.49],
    ["Ice Cream — Vanilla", 4.49],
    ["Sourdough Bread", 3.99],
    ["Whole Wheat Bread", 3.49],
    ["Tortillas — Flour", 2.69],
  ]),
];
